// Synthetic multichannel EEG generator. Runs the whole pipeline with no broker.
// Produces plausible background rhythms plus optional blink (low-freq, frontal) and
// EMG (high-freq bursts) artifacts, so denoising has something visible to remove.

import { Emitter } from '../events.js';

export class SyntheticSource extends Emitter {
  constructor({ channels, rate, chunk = 32, artifacts = true, spatial = true }) {
    super();
    this.channels = channels;
    this.rate = rate;
    this.chunk = chunk;
    this.artifacts = artifacts;
    this.spatial = spatial;
    this.t = 0;                  // absolute sample index
    this._timer = null;
    // per-channel phase offsets so channels aren't identical (non-spatial mode)
    this._phase = Array.from({ length: channels }, (_, c) => c * 0.7);
    // per-channel 1/f (pink-ish) background state, generated by low-passing white noise
    this._pink = new Float32Array(channels);
    this._blinkUntil = -1; this._emgUntil = -1;

    // ---- spatial model ----
    // Electrodes laid on a 1-D scalp axis 0 (frontal) .. 1 (occipital). A handful of
    // cortical "sources" each have ONE shared time series and a smooth spatial topography;
    // channels are their linear mixture (+ small local noise) — the instantaneous-mixing
    // model ICA / IC-U-Net assume, so nearby channels are genuinely correlated and the
    // data is low-rank rather than 30 independent signals.
    const denom = Math.max(1, channels - 1);
    this._pos = Array.from({ length: channels }, (_, c) => c / denom);
    const topo = (center, width) =>
      Float32Array.from(this._pos, (p) => Math.exp(-((p - center) ** 2) / (2 * width * width)));
    this._sources = [
      { f: 2.0,  amp: 6.0,  topo: topo(0.35, 0.60), mod: false }, // delta, broad
      { f: 6.0,  amp: 4.5,  topo: topo(0.50, 0.45), mod: false }, // theta, central
      { f: 10.0, amp: 16.0, topo: topo(0.85, 0.26), mod: true  }, // alpha, posterior-dominant
      { f: 18.0, amp: 4.5,  topo: topo(0.60, 0.35), mod: false }, // beta, centro-parietal
    ];
    this._sPhase = this._sources.map((_, i) => i * 1.3);
    this._fields = [                                              // broad shared 1/f fields
      { amp: 7.0, topo: topo(0.20, 0.55), state: 0 },
      { amp: 6.0, topo: topo(0.78, 0.55), state: 0 },
    ];
    this._blinkTopo = topo(0.04, 0.30);   // blink: frontal
    this._emgTopo = topo(0.28, 0.16);     // EMG: focal, temporal-ish
    // movement/pop: sharp impulse, single-sign Gaussian topography centred on the array.
    // Localized enough to be spatially distinct (so ICA isolates it into one stable
    // high-kurtosis component), but with NO sign change — a dipole's null-line channels
    // clean poorly/overshoot, which a same-sign bump avoids. Every channel gets a real
    // share of the pop (peak mid, ~0.25 at the edges).
    this._popTopo = topo(0.50, 0.30);
  }

  // approx normal via averaged uniforms (Irwin–Hall), zero-mean unit-ish scale
  _randn() { return (Math.random() + Math.random() + Math.random() - 1.5) * 1.15; }

  start() {
    if (this._timer) return;
    const dtMs = (this.chunk / this.rate) * 1000;
    this.emit('status', { source: 'synthetic', state: 'streaming', rate: this.rate });
    this._timer = setInterval(() => this._tick(), dtMs);
  }
  stop() {
    if (this._timer) { clearInterval(this._timer); this._timer = null; }
    this.emit('status', { source: 'synthetic', state: 'stopped' });
  }

  _tick() {
    const n = this.chunk, fs = this.rate;
    const chans = [];
    // schedule artifacts randomly
    if (this.artifacts && this.t > this._blinkUntil && Math.random() < 0.05) {
      this._blinkUntil = this.t + Math.round(0.3 * fs); // ~300 ms blink, ~every ~2 s
    }
    if (this.artifacts && this.t > this._emgUntil && Math.random() < 0.03) {
      this._emgUntil = this.t + Math.round(0.4 * fs);    // ~400 ms EMG burst
    }
    for (let c = 0; c < this.channels; c++) chans.push(new Float32Array(n));

    const denom = Math.max(1, this.channels - 1);
    for (let i = 0; i < n; i++) {
      const idx = this.t + i;
      const ti = idx / fs;
      const blink = idx < this._blinkUntil;
      const emg = idx < this._emgUntil;
      // alpha waxes and wanes at ~0.2 Hz (posterior-dominant spindling)
      const alphaMod = 0.55 + 0.45 * Math.sin(2 * Math.PI * 0.2 * ti);
      const blinkShape = blink
        ? 60 * Math.sin(Math.PI * (idx - (this._blinkUntil - 0.3 * fs)) / (0.3 * fs)) : 0;

      if (this.spatial) {
        // shared source samples at this instant, mixed into channels by topography
        for (const fld of this._fields) fld.state = 0.97 * fld.state + 0.30 * this._randn();
        const s = this._sources.map((src, k) =>
          src.amp * (src.mod ? alphaMod : 1) * Math.sin(2 * Math.PI * src.f * ti + this._sPhase[k]));
        const emgShape = emg ? 25 * this._randn() : 0;
        // electrode pop: rare 1-sample impulse, shared via a focal topography -> a single
        // very-high-kurtosis independent component ICA can isolate and ORICA can reject.
        const pop = (this.artifacts && Math.random() < 0.006) ? (Math.random() < 0.5 ? -1 : 1) * 150 : 0;
        for (let c = 0; c < this.channels; c++) {
          this._pink[c] = 0.97 * this._pink[c] + 0.30 * this._randn();
          let v = 2.0 * this._pink[c] + 0.8 * this._randn();          // small local/decorrelated part
          for (let k = 0; k < this._sources.length; k++) v += this._sources[k].topo[c] * s[k];
          for (const fld of this._fields) v += fld.amp * fld.topo[c] * fld.state;
          if (blink) v += this._blinkTopo[c] * blinkShape;             // spatially-coherent frontal blink
          if (emg) v += this._emgTopo[c] * emgShape;                   // focal EMG
          if (pop) v += this._popTopo[c] * pop;                        // impulsive electrode pop
          chans[c][i] = v;
        }
      } else {
        for (let c = 0; c < this.channels; c++) {
          const ph = this._phase[c];
          const posterior = 0.4 + 0.6 * (c / denom);   // alpha grows toward higher-index channels
          // 1/f background: low-passed white noise (leaky integrator) => pink-ish drift
          this._pink[c] = 0.97 * this._pink[c] + 0.30 * this._randn();
          let v = 7.0 * this._pink[c]                                       // 1/f background
                + 6.0 * Math.sin(2 * Math.PI * 2.0 * ti + 0.10 * ph)        // delta ~2 Hz
                + 4.5 * Math.sin(2 * Math.PI * 6.0 * ti + 0.30 * ph)        // theta ~6 Hz
                + 12.0 * posterior * alphaMod * Math.sin(2 * Math.PI * 10.0 * ti + ph) // alpha ~10 Hz
                + 3.5 * Math.sin(2 * Math.PI * 18.0 * ti + 1.7 * ph)        // beta ~18 Hz
                + 1.4 * this._randn();                                      // white sensor noise
          if (blink) v += Math.max(0, 1 - c / this.channels) * blinkShape;  // frontal-weighted blink
          if (emg) v += 25 * this._randn();                                 // broadband EMG
          chans[c][i] = v;
        }
      }
    }
    this.t += n;
    this.emit('data', { nChannels: this.channels, nSamples: n, t: Date.now(), channels: chans });
  }
}
